# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a02ed770e1dd2a631b9075e92d997b0f12fd165f8c5e7b9b7826450c35c1056e8f71be4ad331db6c978397ebd13767b532ce38138a9f311821c0204da4ec1c6
  facebook_app_id: 540517409456045
  facebook_app_secret: aef776a379419b206c0d9620ff598a9c

test:
  secret_key_base: c16910de4af4c7e7dd1b492fcf1a5cda60712450501988c926b09027eabe0b55c7b574390572f5f03626594cdc781f617879083eb7da932031fecd366c7d529f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
